# NumPy Arrays

In [ ]:
my_list = [1,2,3]

In [7]:
import numpy as np

In [17]:
arr = np.array(my_list)

In [18]:
arr

array([1, 2, 3])

In [20]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [21]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])